[tool.poetry]
name = "concepts"
version = "0.1.0"
description = ""
authors = ["Ryan Selesnik <ryan.selesnik@garmin.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
